name: 🐛 Bug Report
description: Report a bug in multi_dropdown
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below to help us fix it.

  - type: input
    id: version
    attributes:
      label: Package version
      description: Which version of `multi_dropdown` are you using?
      placeholder: "3.0.0"
    validations:
      required: true

  - type: input
    id: flutter-version
    attributes:
      label: Flutter version
      description: Output of `flutter --version`
      placeholder: "Flutter 3.x.x"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) does this affect?
      multiple: true
      options:
        - Android
        - iOS
        - Web
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A clear description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal steps or code to reproduce the bug.
      value: |
        1. 
        2. 
        3.
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal reproduction code
      description: Paste the minimal Dart code that demonstrates the issue.
      render: dart

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Recordings
      description: If applicable, add screenshots or recordings.

  - type: textarea
    id: logs
    attributes:
      label: Logs / Stack trace
      description: Any relevant error output.
      render: shell
