name: Flutter analyze

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flutter-analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze formatting
        run: dart format . --set-exit-if-changed

      - name: Analyze project source
        run: flutter analyze --no-pub

      - name: Install pana
        run: dart pub global activate pana

      - name: Analyze project source with pana
        run: pana
